---
- name: PING
  hosts: LOKI-SW
  no_log: false
  gather_facts: false
  connection: network_cli

  tasks:
          - name: PING 8.8.8.8
            ios_command:
                    commands:
                            - ping 8.8.8.8 repeat 20 source vlan900
            register: OUTPUT

          - name: OUTPUT
            debug:
              msg: "{{ OUTPUT.stdout }}"




