---
- name: SHOW RUNNING-CONFIG
  hosts: LOKI-RTR
  no_log: false
  gather_facts: false
  connection: network_cli

  tasks:
          - name: DISPLAY THE RUNNING-CONFIG
            ios_command:
                    commands:
                            - show running-config
            register: salida

          - name: SAVE OUTPUT TO ./backups-Cisco/
            debug:
              msg: "{{ salida.stdout }}"
           



